extends Node

enum PROP_TYPE {SPRING}
enum DRAWABLE_OBSTACLE_TYPES { NORMAL, WORLD_INTERACTIVE }
enum SERIALISABLE_TYPES { DRAWABLE_OBSTACLE, PROP }
enum PROP_INTERACTION_STATE {PLACING, PLACED, INACTIVE }
